require 'nfg-rest-client/version'
require 'nfg-rest-client/logger'
require 'nfg-rest-client/configuration'
require 'flexirest'
require 'nfg-rest-client/faraday_config'
require 'nfg-rest-client/models/base'
require 'nfg-rest-client/models/access_token'
require 'nfg-rest-client/models/donation'

# require 'nfg-rest-client/utils'
# require 'nfg-rest-client/client'
